In [1]:
from torch import nn
import torch
import time
    
class Model_Mul1_4_v1(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear_layer_stack = nn.Sequential(
            nn.Linear(323, 646),
            nn.ReLU(inplace=True),
            nn.Linear(646, 230),
            nn.ReLU(inplace=True),
            nn.Linear(230, 115),
            nn.ReLU(inplace=True),
            nn.Linear(115, 5)
        )

    def forward(self, x):
        return self.linear_layer_stack(x)

In [2]:
# Mudando todos os valores dos pesos para 0,3 e dos bias para 0,5
class Model_Mul1_4_v2(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear_layer_stack = nn.Sequential(
            nn.Linear(750, 2000),
            nn.ReLU(inplace=True),
            nn.Linear(2000, 500),
            nn.ReLU(inplace=True),
            nn.Linear(500, 100),
            nn.ReLU(inplace=True),
            nn.Linear(100, 3)
        )

    def forward(self, x):
        return self.linear_layer_stack(x)   

In [3]:
class DNN(nn.Module):
        def __init__(self, input_size, output_size):
            super(DNN, self).__init__()
            self.linear_layer_stack = nn.Sequential(
                nn.Linear(input_size, 256),
                nn.LeakyReLU(inplace=True),
                nn.Linear(256, 128),
                nn.LeakyReLU(inplace=True),
                nn.Linear(128, output_size),
                nn.Softmax(dim=1) if output_size > 1 else nn.Sigmoid()
            )

        def forward(self, x):
            return self.linear_layer_stack(x)
        
count_parameters(DNN(14 + 14 + 3, 2))

41346

In [2]:
#  Quantidade de parametros livres do modelo Model_Mul1_4_v1
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

count_parameters(Model_Mul1_4_v1())

385259

In [4]:
# Cria um vetor de entrada com 323 elementos em 1
input_vector = torch.ones(323)

model = Model_Mul1_4_v1()

times2run = 50000

start_time = time.time()

for i in range(times2run):
    model(input_vector)

end_time = time.time()

print("Tempo total: ", end_time - start_time)
print("Tempo médio: ", (end_time - start_time)/times2run)

model(input_vector)

Tempo total:  6.430840015411377
Tempo médio:  0.00012861680030822753


tensor([-0.0370, -0.0820, -0.1709, -0.0816,  0.1030], grad_fn=<AddBackward0>)

In [24]:
model(input_vector)

tensor([0.5493, 0.5493, 0.5493, 0.5493, 0.5493], grad_fn=<AddBackward0>)

In [16]:
model(input_vector)

tensor([44935800., 44935800., 44935800., 44935800., 44935828.],
       grad_fn=<AddBackward0>)

In [17]:
model(input_vector)

tensor([44935800., 44935800., 44935800., 44935800., 44935828.],
       grad_fn=<AddBackward0>)

In [ ]:
class NN:
    def __init__(self, inputSize, hidden1Size, hidden2Size, hidden3Size, outputSize) -> None:
        self.weights1 = self.initializeWeights(inputSize, hidden1Size)
        self.weights2 = self.initializeWeights(hidden1Size, hidden2Size)
        self.weights3 = self.initializeWeights(hidden2Size, hidden3Size)
        self.weightsOutput = self.initializeWeights(hidden3Size, outputSize)


        private double[][] weights1; // Pesos da primeira camada oculta
    private double[][] weights2; // Pesos da segunda camada oculta
    private double[][] weights3; // Pesos da terceira camada oculta
    private double[][] weightsOutput; // Pesos da camada de saída

    private double[] biases1; // Biases da primeira camada oculta
    private double[] biases2; // Biases da segunda camada oculta
    private double[] biases3; // Biases da terceira camada oculta
    private double[] biasesOutput; // Biases da camada de saída

    def initializeWeights(self, inSize, outSize):
        return [[0.003 for i in range(inSize)] for j in range(outSize)]

In [26]:
import numpy as np

class NeuralNetwork:
    def __init__(self, input_size, hidden1_size, hidden2_size, hidden3_size, output_size):
        # Inicializar pesos e biases com valores aleatórios
        self.weights1 = self.initialize_weights(input_size, hidden1_size)
        self.weights2 = self.initialize_weights(hidden1_size, hidden2_size)
        self.weights3 = self.initialize_weights(hidden2_size, hidden3_size)
        self.weights_output = self.initialize_weights(hidden3_size, output_size)

        self.biases1 = self.initialize_biases(hidden1_size)
        self.biases2 = self.initialize_biases(hidden2_size)
        self.biases3 = self.initialize_biases(hidden3_size)
        self.biases_output = self.initialize_biases(output_size)

    def initialize_weights(self, in_size, out_size):
        # Implementar a lógica para inicializar pesos aleatórios
        return np.ones((out_size, in_size)) * 0.003

    def initialize_biases(self, size):
        # Implementar a lógica para inicializar biases aleatórios
        return np.ones(size) * 0.05

    def relu(self, x):
        # Implementar a função de ativação ReLU
        return np.maximum(0, x)

    def softmax(self, x):
        # Implementar a função de ativação Softmax
        exp_values = np.exp(x)
        return exp_values / np.sum(exp_values)

    def matrix_vector_multiplication(self, vector, matrix):
        # Implementar a multiplicação de vetor por matriz
        return np.dot(vector, matrix)

    def vector_vector_sum(self, vector1, vector2):
        # Implementar a soma de vetores
        return vector1 + vector2

    def predict(self, input_data):
        # Propagação para frente (forward propagation)
        product1 = self.matrix_vector_multiplication(input_data, self.weights1)
        hidden1 = self.relu(self.vector_vector_sum(product1, self.biases1))

        product2 = self.matrix_vector_multiplication(hidden1, self.weights2)
        hidden2 = self.relu(self.vector_vector_sum(product2, self.biases2))

        product3 = self.matrix_vector_multiplication(hidden2, self.weights3)
        hidden3 = self.relu(self.vector_vector_sum(product3, self.biases3))

        product_output = self.matrix_vector_multiplication(hidden3, self.weights_output)
        output = self.vector_vector_sum(product_output, self.biases_output)

        return output

# Exemplo de uso
input_size = 323
hidden1_size = 646
hidden2_size = 230
hidden3_size = 115
output_size = 5

neural_network = NeuralNetwork(input_size, hidden1_size, hidden2_size, hidden3_size, output_size)

input_data = np.ones(input_size)

output = neural_network.predict(input_data)


ValueError: shapes (323,) and (646,323) not aligned: 323 (dim 0) != 646 (dim 0)