In [82]:
import pandas as pd
import numpy as np
np.random.seed(111) # Fixa a semente do gerador de números aleatórios do numpy. Para que os resultados sejam sempre os mesmos.

# Cria um data frame com as colunas 'req' e s_{0} até s_{20}. Com um total de 30 amostras. As coluna 'req' assume valores de 2, 3, 5. Enquantos as colunas s_{0} até s_{20} assumem valores de 0 ou 1.
SAMPLE = 10
SLOTS = 32
reqNumbOfSlots = np.random.choice([2, 3, 5], SAMPLE)
s = np.random.choice([0, 1], (SAMPLE, SLOTS), p=[0.6, 0.4])
df = pd.DataFrame(data=s, columns=['s_{}'.format(i) for i in range(SLOTS)])
df['req'] = reqNumbOfSlots


df

s_0  s_1  s_2  s_3  s_4  s_5  s_6  s_7  s_8  s_9  ...  s_23  s_24  s_25  \
0    0    1    1    1    1    0    0    0    1    0  ...     0     1     1   
1    0    0    0    1    1    0    1    0    0    1  ...     0     0     0   
2    1    0    0    0    1    0    0    0    1    0  ...     1     1     0   
3    1    1    0    1    1    0    0    1    1    1  ...     0     0     0   
4    1    0    1    0    0    0    1    0    1    0  ...     0     0     1   
5    0    1    0    0    0    1    0    0    1    1  ...     0     0     0   
6    1    0    1    1    0    1    1    1    0    1  ...     1     0     0   
7    1    1    1    0    0    1    0    0    0    1  ...     1     0     1   
8    0    1    1    1    0    0    1    1    0    0  ...     0     0     1   
9    0    0    1    0    0    0    1    1    0    0  ...     0     0     1   

   s_26  s_27  s_28  s_29  s_30  s_31  req  
0     0     0     0     0     1     0    2  
1     1     1     0     1     0     0    2  
2     1     1     0     0     0     0    2  
3     1     0     0     1     1     1    2  
4     0     1     1     0     0     0    5  
5     1     0     1     0     0     0    3  
6     0     1     1     1     0     1    5  
7     0     0     0     0     1     1    5  
8     0     0     0     1     0     0    5  
9     0     0     1     0     0     0    2  

[10 rows x 33 columns]

In [83]:
s_cols = ['s_{}'.format(i) for i in range(SLOTS)]

N_REGIONS = 8

if SLOTS % N_REGIONS != 0:
    raise ValueError('Number of slots must be divisible by number of regions.')

# Percorre todas as linhas do data frame
for row in df.iloc:
    
    demand = row['req']

    # Cria um vetor de disponibilidade de slots para todo o espectro
    availability_vector = row[s_cols].values

    # Percorre todas as regiões
    for region_ID in range(N_REGIONS):
        
        # Verifica se há slots disponíveis na região atual para a demanda atual
        for slot in range((SLOTS // N_REGIONS) * region_ID, (SLOTS // N_REGIONS) * (region_ID + 1)):

            if slot + demand > SLOTS:
                break

            is_available = True
            for j in range(demand):
                if availability_vector[slot + j]:
                    is_available = False
                    break
            if is_available:
                
                # Escreve True na linha atual e coluna atual 'region_{region_ID}'
                df.at[row.name, 'region_{}'.format(region_ID)] = True
                break

        # Se não houver slots disponíveis para a demanda atual, escreve False em todas as colunas 'region_{region_ID}'
        if not is_available:
            df.at[row.name, 'region_{}'.format(region_ID)] = False



    print(availability_vector)

df

[0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 0 1 1 1 1 0 1 0 1 1 0 0 0 0 1 0]
[0 0 0 1 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0 1 1 0 1 0 0]
[1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 1 0 1 1 1 0 1 1 0 0 0 0]
[1 1 0 1 1 0 0 1 1 1 0 1 1 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1 1 1]
[1 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 0]
[0 1 0 0 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0]
[1 0 1 1 0 1 1 1 0 1 0 0 0 0 1 0 0 1 0 1 0 1 1 1 0 0 0 1 1 1 0 1]
[1 1 1 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1]
[0 1 1 1 0 0 1 1 0 0 0 1 0 1 1 1 1 1 1 1 0 1 0 0 0 1 0 0 0 1 0 0]
[0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 0]


s_0  s_1  s_2  s_3  s_4  s_5  s_6  s_7  s_8  s_9  ...  s_31  req  region_0  \
0    0    1    1    1    1    0    0    0    1    0  ...     0    2     False   
1    0    0    0    1    1    0    1    0    0    1  ...     0    2      True   
2    1    0    0    0    1    0    0    0    1    0  ...     0    2      True   
3    1    1    0    1    1    0    0    1    1    1  ...     1    2     False   
4    1    0    1    0    0    0    1    0    1    0  ...     0    5     False   
5    0    1    0    0    0    1    0    0    1    1  ...     0    3      True   
6    1    0    1    1    0    1    1    1    0    1  ...     1    5     False   
7    1    1    1    0    0    1    0    0    0    1  ...     1    5     False   
8    0    1    1    1    0    0    1    1    0    0  ...     0    5     False   
9    0    0    1    0    0    0    1    1    0    0  ...     0    2      True   

   region_1  region_2  region_3  region_4  region_5  region_6  region_7  
0      True     False     False     False     False      True      True  
1      True      True      True      True      True      True      True  
2      True      True      True      True     False     False      True  
3      True     False      True     False      True      True     False  
4     False     False     False     False     False     False     False  
5     False     False     False      True      True     False      True  
6     False     False     False     False     False     False     False  
7     False     False     False     False     False     False     False  
8     False     False     False     False     False     False     False  
9      True      True      True      True      True      True      True  

[10 rows x 41 columns]

Modelo de região levando em consideração o primeiro slot possível para alocar a demanda.

In [84]:
import numpy as np
import pandas as pd

np.random.seed(111)

reqNumbOfSlots = np.random.choice([2, 3, 5], SAMPLE)
s = np.random.choice([0, 1], (SAMPLE, SLOTS), p=[0.6, 0.4])
df = pd.DataFrame(data=s, columns=['s_{}'.format(i) for i in range(SLOTS)])
df['req'] = reqNumbOfSlots

#print(df)

def check_availability(row, demand, slots, region_id):
    availability_vector = row[slots].values
    region_start = (len(slots) // N_REGIONS) * region_id
    region_end = (len(slots) // N_REGIONS) * (region_id + 1)

    for slot in range(region_start, region_end):
        if slot + demand > SLOTS:
            return False
        if not np.any(availability_vector[slot:slot + demand]):
            return True
    return False

for region_ID in range(N_REGIONS):
    region_col = 'region_{}'.format(region_ID)
    region_start = (SLOTS // N_REGIONS) * region_ID
    region_end = (SLOTS // N_REGIONS) * (region_ID + 1)
    
    df[region_col] = df.apply(lambda row: check_availability(row, row['req'], s_cols, region_ID), axis=1)

df

s_0  s_1  s_2  s_3  s_4  s_5  s_6  s_7  s_8  s_9  ...  s_31  req  region_0  \
0    0    1    1    1    1    0    0    0    1    0  ...     0    2     False   
1    0    0    0    1    1    0    1    0    0    1  ...     0    2      True   
2    1    0    0    0    1    0    0    0    1    0  ...     0    2      True   
3    1    1    0    1    1    0    0    1    1    1  ...     1    2     False   
4    1    0    1    0    0    0    1    0    1    0  ...     0    5     False   
5    0    1    0    0    0    1    0    0    1    1  ...     0    3      True   
6    1    0    1    1    0    1    1    1    0    1  ...     1    5     False   
7    1    1    1    0    0    1    0    0    0    1  ...     1    5     False   
8    0    1    1    1    0    0    1    1    0    0  ...     0    5     False   
9    0    0    1    0    0    0    1    1    0    0  ...     0    2      True   

   region_1  region_2  region_3  region_4  region_5  region_6  region_7  
0      True     False     False     False     False      True      True  
1      True      True      True      True      True      True      True  
2      True      True      True      True     False     False      True  
3      True     False      True     False      True      True     False  
4     False     False     False     False     False     False     False  
5     False     False     False      True      True     False      True  
6     False     False     False     False     False     False     False  
7     False     False     False     False     False     False     False  
8     False     False     False     False     False     False     False  
9      True      True      True      True      True      True      True  

[10 rows x 41 columns]